### ISSUE TITLE
[Request] - Add support for rearranging, blacklisting, and resizing

### ISSUE THREAD

**Issue by EricWagnerJr** [pg8wood/OSRS-touch-bar#12]
Wanted to do some vorkath on my MBP w/touchbar and stumbled upon this. Noticed that the buttons are relatively small for switching without paying attention. I'm gonna take a swing at it but I need to switch between my inventory and my spell book and they are 3 buttons apart and non-rearrangeable. Do you think this would be possible? The progress you have, though, looks great!

**Comment by pg8wood** [comment]
Yes! The next thing on my radar is to allow the user to rearrange and toggle the buttons.

**Comment by pg8wood** [comment]
@EricWagnerJr thanks for the suggestion! I think you'll enjoy the latest release. If you have more ideas, I'd love to hear em!
