### ISSUE TITLE
[Bug] - Was moving around the different icons and the spacing is off between two icons

### ISSUE THREAD

**Issue by EricWagnerJr** [pg8wood/OSRS-touch-bar#15]
I removed the combat styles and it returned to normal. I placed it back and then there was a gap. 

Edit: just found out the image format is HEIC so I'm gonna figure that out and post it.

Edit2: should be good
![img_5358](https://user-images.githubusercontent.com/39307812/46485523-6e6c3180-c7c1-11e8-8e87-30eb82bc054f.jpg)

**Comment by pg8wood** [comment]
Had to put this off for awhile, but it turns out this was a super simple fix!
