### ISSUE TITLE
macOS 10.14.5 security update prevents keypresses from firing

### ISSUE THREAD

**Issue by victor00100** [pg8wood/OSRS-touch-bar#17]
Hello, I am using runelite and when pressing the keys in the touch bar nothing happes, if i try using the funtion keys it works.

What could be the cause of this?

Greetings

**Comment by pg8wood** [comment]
Hey @victor00100, it looks like the new macOS Mojave security update broke the app. Thanks for opening this issue! I'll take a look into it.

**Comment by victor00100** [comment]
Okay no probs, good luck!

**Comment by pg8wood** [comment]
@victor00100, [new version](https://github.com/pg8wood/OSRS-touch-bar/releases/tag/v1.2.1) is up! You _may_ need to uninstall the old version first in order for the new privacy settings to take effect. Thanks again for bringing this to my attention!
