### ISSUE TITLE
macOS Catalina Notarization needed

### ISSUE THREAD

**Issue by pg8wood** [pg8wood/OSRS-touch-bar#18]
Let's avoid those scary warning messages that will appear on apps that aren't notarized by Apple.

See: https://developer.apple.com/news/?id=09032019a

**Comment by knakamura13** [comment]
Is there a workaround to run OSRS Touch Bar on Catalina?

**Comment by pg8wood** [comment]
Hey @knakamura13, after working with Apple for awhile regarding a bug in Xcode that was preventing the app notarization, the [latest release](https://github.com/pg8wood/OSRS-touch-bar/releases/tag/v1.2.2) is notarized. Please let me know if you continue to see any issues!
